/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список workflow
         * @description Возвращает список всех workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowMeta"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Создать workflow
         * @description Создаёт новый workflow без привязки к проекту.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные для создания workflow. */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Название workflow. */
                        name: string;
                        /** @description Описание workflow. */
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Workflow успешно создан. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить workflow
         * @description Возвращает метаданные и актуальный граф workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Обновить метаданные workflow
         * @description Обновляет базовые поля workflow (название, описание).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            /** @description Новые метаданные workflow. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkflowMetaUpdate"];
                };
            };
            responses: {
                /** @description Метаданные workflow обновлены. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowMeta"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Удалить workflow
         * @description Полностью удаляет workflow и связанные данные.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workflow удалён. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список версий workflow
         * @description Возвращает все логические версии указанного workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список версий для workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowVersion"][];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Создать версию workflow
         * @description Создаёт логическую версию workflow и привязывает её к текущему графу.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Версия workflow создана. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowVersion"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-versions/{versionId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Обновить граф версии workflow
         * @description Полностью заменяет граф (ноды и связи) для указанной версии workflow.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор версии workflow. */
                    versionId: components["parameters"]["VersionId"];
                };
                cookie?: never;
            };
            /** @description Новый граф workflow. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkflowGraph"];
                };
            };
            responses: {
                /** @description Граф для версии workflow обновлён. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowGraph"];
                    };
                };
                /** @description Версия workflow не найдена. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список снепшотов workflow
         * @description Возвращает все именованные снепшоты текущего workflow (новые сверху).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список снепшотов. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowSnapshot"][];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Создать снепшот текущего графа
         * @description Фиксирует текущую ревизию workflow под человекочитаемым именем — можно вернуться к ней позже.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSnapshotRequest"];
                };
            };
            responses: {
                /** @description Снепшот создан. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowSnapshot"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/snapshots/{snapshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить снепшот
         * @description Удаляет снепшот. Сама ревизия графа остаётся в истории (на неё могут ссылаться runs).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                    snapshotId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Снепшот удалён. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Снепшот не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/snapshots/{snapshotId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Откатить workflow на состояние снепшота
         * @description Создаёт новую ревизию с графом из снепшота и делает её текущей. История не теряется — откат сам становится точкой в истории, и старые runs продолжают ссылаться на свои ревизии.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                    snapshotId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Граф восстановлен из снепшота. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowGraph"];
                    };
                };
                /** @description Снепшот или workflow не найдены. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список триггеров workflow
         * @description Возвращает все триггеры workflow. Триггеры создаются/удаляются автоматически при сохранении графа (по нодам с type trigger.webhook/cron/interval).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список триггеров для workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trigger"][];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/triggers/{triggerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Включить/выключить триггер
         * @description Переключает поле `enabled` у триггера. Для cron/interval включение пере-планирует таск, выключение — отменяет. Для webhook отключённый триггер возвращает 404 при вызове по токену.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                    /** @description Идентификатор триггера. */
                    triggerId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TriggerUpdate"];
                };
            };
            responses: {
                /** @description Обновлённый триггер. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trigger"];
                    };
                };
                /** @description Триггер или workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/webhook/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запуск workflow по webhook
         * @description Принимает входящий webhook и инициирует запуск связанного workflow.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Публичный токен webhook-триггера. */
                    token: components["parameters"]["Token"];
                };
                cookie?: never;
            };
            /** @description Необязательное тело запроса, которое будет передано в workflow. */
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Запуск workflow принят в обработку. */
                202: {
                    headers: {
                        /** @description Абсолютный URL для опроса итогового результата запуска (GET /workflow-runs/{runId}/result). */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookAccepted"];
                    };
                };
                /** @description Webhook с таким токеном не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список запусков workflow
         * @description Возвращает историю запусков указанного workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список запусков для workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowRun"][];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Ручной запуск workflow
         * @description Запускает выполнение workflow вручную. Принимает произвольный JSON в теле — он будет доступен нодам как `runInput`. Опционально через `startNodeId` можно стартовать только подграф, достижимый из конкретной ноды.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Если указан — исполняем только subgraph, достижимый из этой ноды. */
                    startNodeId?: string;
                };
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            /** @description Произвольный JSON-payload, прокидывается в `runInput` для нод без входов. */
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Запуск workflow принят. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowRun"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/ab-analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Аналитика по выбранной A/B-ноде workflow. */
        get: {
            parameters: {
                query: {
                    abNodeId: string;
                };
                header?: never;
                path: {
                    workflowId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AbAnalyticsResponse"];
                    };
                };
                /** @description BAD REQUEST (node is not an A/B split, or abNodeId blank) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description NOT FOUND (workflow or node) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить запуск workflow
         * @description Возвращает статус и информацию о конкретном запуске workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор запуска workflow. */
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о запуске workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowRun"];
                    };
                };
                /** @description Запуск не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-runs/{runId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить агрегированный результат запуска
         * @description Возвращает только итог пайплайна (без поноды-разбивки): статус, тайминги и output терминальных нод. Если терминальная нода одна — её output как есть, иначе объект {nodeId: output} по терминальным.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор запуска workflow. */
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Итоговый результат запуска. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowRunResult"];
                    };
                };
                /** @description Запуск не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node-runs/{nodeRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить запуск ноды
         * @description Возвращает детали выполнения отдельной ноды.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор запуска отдельной ноды. */
                    nodeRunId: components["parameters"]["NodeRunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о выполнении ноды. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodeRun"];
                    };
                };
                /** @description Запуск ноды не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Полное представление workflow, включающее метаданные и граф. */
        Workflow: {
            meta?: components["schemas"]["WorkflowMeta"];
            graph?: components["schemas"]["WorkflowGraph"];
        };
        /** @description Метаданные workflow. */
        WorkflowMeta: {
            /** @description Идентификатор workflow. */
            id?: string;
            /** @description Название workflow. */
            name?: string;
            /** @description Описание workflow. */
            description?: string;
            /** @description Признак демонстрационного workflow (создан seeder'ом на старте). */
            isDemo?: boolean;
            /** @description Количество нод в текущей ревизии workflow. */
            nodesCount?: number;
            /** @description Время создания в ISO 8601. */
            createdAt?: string;
            /** @description Время последнего изменения в ISO 8601. */
            updatedAt?: string;
        };
        /** @description Изменяемые поля метаданных workflow. */
        WorkflowMetaUpdate: {
            /** @description Новое название workflow. */
            name?: string;
            /** @description Новое описание workflow. */
            description?: string;
        };
        /** @description Логическая версия workflow. */
        WorkflowVersion: {
            /** @description Идентификатор версии workflow. */
            id?: string;
            /** @description Идентификатор связанного workflow. */
            workflowId?: string;
            /** @description Опциональный тег версии (например, v1.0.0). */
            tag?: string;
            /** @description Дата создания версии в ISO 8601. */
            createdAt?: string;
        };
        /** @description Именованный снепшот графа workflow — точка восстановления поверх автосейва. */
        WorkflowSnapshot: {
            /** @description Идентификатор снепшота. */
            id?: string;
            /** @description Идентификатор связанного workflow. */
            workflowId?: string;
            /** @description Человекочитаемое имя снепшота (например, "перед релизом v1.2"). */
            name?: string;
            /** @description Опциональный комментарий. */
            description?: string | null;
            /** @description Дата создания снепшота в ISO 8601. */
            createdAt?: string;
        };
        CreateSnapshotRequest: {
            /** @description Имя снепшота (обязательное, не пустое). */
            name: string;
            /** @description Опциональный комментарий. */
            description?: string | null;
        };
        /** @description Граф workflow, включающий ноды и связи. */
        WorkflowGraph: {
            /** @description Идентификатор версии, которой принадлежит граф. */
            versionId?: string;
            /** @description Список нод workflow. */
            nodes: components["schemas"]["Node"][];
            /** @description Список соединений между нодами. */
            connections: components["schemas"]["Connection"][];
        };
        /** @description Нода workflow. */
        Node: {
            /** @description Идентификатор ноды. */
            id?: string;
            /** @description Тип ноды (trigger, http, ab-fork и т.д.). */
            type?: string;
            /** @description Координаты ноды в редакторе графа. */
            position?: {
                /** @description Координата X. */
                x?: number;
                /** @description Координата Y. */
                y?: number;
            };
            /** @description Конфигурация ноды и дополнительные данные. */
            data?: {
                /** @description Человекочитаемое название ноды. */
                label?: string;
                /** @description Произвольная конфигурация ноды. */
                config?: Record<string, never>;
                /** @description Конфигурация A/B-теста для ноды, если применимо. */
                abConfig?: Record<string, never>;
            };
        };
        /** @description Соединение между двумя нодами workflow. */
        Connection: {
            /** @description Идентификатор соединения. */
            id: string;
            /** @description ID исходной ноды. */
            source: string;
            /** @description ID целевой ноды. */
            target: string;
            /** @description Метка исходящего порта (например, 'A' или 'B'). */
            sourceHandle?: string;
            /** @description Метка входящего порта. */
            targetHandle?: string;
        };
        /** @description Триггер запуска workflow, привязанный к ноде в графе. */
        Trigger: {
            /** @description Идентификатор триггера. */
            id?: string;
            /** @description Идентификатор workflow. */
            workflowId?: string;
            /** @description Идентификатор ноды в графе, к которой привязан триггер. */
            nodeId?: string;
            /** @description Тип триггера (webhook, cron, interval). */
            type?: string;
            /** @description Конфигурация триггера (например, cron-выражение, everySeconds). */
            config?: Record<string, never>;
            /** @description Публичный токен для webhook-триггера (генерируется на бэке). */
            token?: string;
            /** @description Активен ли триггер. Для cron/interval отключённый триггер не запускается по расписанию. Для webhook отключённый триггер возвращает 404 при попытке вызова. */
            enabled?: boolean;
        };
        /** @description Тело для PATCH триггера — переключение активности. */
        TriggerUpdate: {
            /** @description Включить (true) или выключить (false) триггер. */
            enabled: boolean;
        };
        /** @description Один запуск workflow. */
        WorkflowRun: {
            /** @description Идентификатор запуска. */
            id?: string;
            /** @description Идентификатор workflow. */
            workflowId?: string;
            /** @description Статус запуска (queued, running, success, failed). */
            status?: string;
            /** @description Время старта запуска (ISO-8601). */
            startedAt?: string;
            /** @description Время завершения запуска (ISO-8601). */
            finishedAt?: string;
            /**
             * Format: int64
             * @description Длительность запуска в миллисекундах. Заполнено только для завершённых запусков.
             */
            durationMs?: number;
            /** @description Входные параметры запуска (что было передано в POST как payload). */
            input?: Record<string, never>;
            /** @description Агрегированный результат выполнения workflow. */
            output?: Record<string, never>;
            /** @description Если запуск стартован с конкретной ноды (subgraph) — её id. */
            startNodeId?: string;
            /** @description Состояние каждой ноды этого запуска в порядке создания node_run-записей. */
            nodes?: components["schemas"]["NodeRun"][];
        };
        /** @description Результат выполнения отдельной ноды. */
        NodeRun: {
            /** @description Идентификатор запуска ноды. */
            id?: string;
            /** @description Идентификатор запуска workflow. */
            workflowRunId?: string;
            /** @description Идентификатор ноды. */
            nodeId?: string;
            /** @description Статус выполнения ноды. */
            status?: string;
            /** @description Время старта ноды. */
            startedAt?: string;
            /** @description Время завершения ноды. */
            finishedAt?: string;
            /** @description Входные данные ноды. */
            input?: Record<string, never>;
            /** @description Выходные данные ноды. */
            output?: Record<string, never>;
            /** @description Текст ошибки, если выполнение завершилось неуспешно. */
            errorMessage?: string;
        };
        /** @description Подтверждение приёма webhook-а с ссылкой на итоговый результат запуска. */
        WebhookAccepted: {
            run: components["schemas"]["WorkflowRun"];
            /**
             * Format: uri
             * @description Абсолютный URL для опроса итогового результата запуска (GET /workflow-runs/{runId}/result).
             */
            pollUrl: string;
        };
        /** @description Итоговый результат пайплайна без поноды-разбивки. */
        WorkflowRunResult: {
            /** @description Идентификатор запуска. */
            id: string;
            /** @description Идентификатор workflow. */
            workflowId: string;
            /** @description Статус запуска (queued/running/success/failed). */
            status: string;
            /** @description Время старта запуска. */
            startedAt?: string;
            /** @description Время завершения запуска. */
            finishedAt?: string;
            /**
             * Format: int64
             * @description Длительность выполнения, мс.
             */
            durationMs?: number;
            /** @description Агрегированный output пайплайна — данные терминальных нод. Если терминальная нода одна — её output как есть, иначе объект {nodeId: output}. Null, пока запуск не завершён или выходов нет. */
            output?: unknown;
        };
        AbAnalyticsResponse: {
            abNodeId: string;
            /** @enum {string} */
            mode: "pick" | "split";
            totalRuns: number;
            excludedNoVariant: number;
            /** Format: date-time */
            computedAt: string;
            variants: components["schemas"]["AbVariantRow"][];
            warnings: string[];
        };
        AbVariantRow: {
            key: string;
            label: string;
            color: string;
            weight?: number | null;
            runs: number;
            trafficCount: number;
            /** Format: double */
            trafficPct: number;
            conversions?: number | null;
            /** Format: double */
            conversionPct?: number | null;
            /** Format: double */
            ciLow?: number | null;
            /** Format: double */
            ciHigh?: number | null;
            /** Format: double */
            liftVsBaseline?: number | null;
            /** Format: double */
            pValue?: number | null;
            isBaseline: boolean;
            isSignificant: boolean;
        };
    };
    responses: never;
    parameters: {
        /** @description Идентификатор workflow. */
        WorkflowId: string;
        /** @description Идентификатор версии workflow. */
        VersionId: string;
        /** @description Публичный токен webhook-триггера. */
        Token: string;
        /** @description Идентификатор запуска workflow. */
        RunId: string;
        /** @description Идентификатор запуска отдельной ноды. */
        NodeRunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
