/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список workflow
         * @description Возвращает список всех workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowMeta"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Создать workflow
         * @description Создаёт новый workflow без привязки к проекту.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные для создания workflow. */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Название workflow. */
                        name: string;
                        /** @description Описание workflow. */
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Workflow успешно создан. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить workflow
         * @description Возвращает метаданные и актуальный граф workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Обновить метаданные workflow
         * @description Обновляет базовые поля workflow (название, описание).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            /** @description Новые метаданные workflow. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkflowMetaUpdate"];
                };
            };
            responses: {
                /** @description Метаданные workflow обновлены. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowMeta"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Удалить workflow
         * @description Полностью удаляет workflow и связанные данные.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workflow удалён. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список версий workflow
         * @description Возвращает все логические версии указанного workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список версий для workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowVersion"][];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Создать версию workflow
         * @description Создаёт логическую версию workflow и привязывает её к текущему графу.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Версия workflow создана. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowVersion"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-versions/{versionId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Обновить граф версии workflow
         * @description Полностью заменяет граф (ноды и связи) для указанной версии workflow.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор версии workflow. */
                    versionId: components["parameters"]["VersionId"];
                };
                cookie?: never;
            };
            /** @description Новый граф workflow. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkflowGraph"];
                };
            };
            responses: {
                /** @description Граф для версии workflow обновлён. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowGraph"];
                    };
                };
                /** @description Версия workflow не найдена. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список триггеров workflow
         * @description Возвращает все триггеры workflow. Триггеры создаются/удаляются автоматически при сохранении графа (по нодам с type trigger.webhook/cron/interval).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список триггеров для workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trigger"][];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запуск workflow по webhook
         * @description Принимает входящий webhook и инициирует запуск связанного workflow.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Публичный токен webhook-триггера. */
                    token: components["parameters"]["Token"];
                };
                cookie?: never;
            };
            /** @description Необязательное тело запроса, которое будет передано в workflow. */
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Запуск workflow принят в обработку. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Webhook с таким токеном не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflowId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список запусков workflow
         * @description Возвращает историю запусков указанного workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список запусков для workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowRun"][];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Ручной запуск workflow
         * @description Запускает выполнение workflow вручную.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор workflow. */
                    workflowId: components["parameters"]["WorkflowId"];
                };
                cookie?: never;
            };
            /** @description Дополнительные параметры запуска. */
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Запуск workflow принят. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowRun"];
                    };
                };
                /** @description Workflow не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить запуск workflow
         * @description Возвращает статус и информацию о конкретном запуске workflow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор запуска workflow. */
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о запуске workflow. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowRun"];
                    };
                };
                /** @description Запуск не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node-runs/{nodeRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить запуск ноды
         * @description Возвращает детали выполнения отдельной ноды.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор запуска отдельной ноды. */
                    nodeRunId: components["parameters"]["NodeRunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о выполнении ноды. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodeRun"];
                    };
                };
                /** @description Запуск ноды не найден. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Полное представление workflow, включающее метаданные и граф. */
        Workflow: {
            meta?: components["schemas"]["WorkflowMeta"];
            graph?: components["schemas"]["WorkflowGraph"];
        };
        /** @description Метаданные workflow. */
        WorkflowMeta: {
            /** @description Идентификатор workflow. */
            id?: string;
            /** @description Название workflow. */
            name?: string;
            /** @description Описание workflow. */
            description?: string;
            /** @description Время создания в ISO 8601. */
            createdAt?: string;
            /** @description Время последнего изменения в ISO 8601. */
            updatedAt?: string;
        };
        /** @description Изменяемые поля метаданных workflow. */
        WorkflowMetaUpdate: {
            /** @description Новое название workflow. */
            name?: string;
            /** @description Новое описание workflow. */
            description?: string;
        };
        /** @description Логическая версия workflow. */
        WorkflowVersion: {
            /** @description Идентификатор версии workflow. */
            id?: string;
            /** @description Идентификатор связанного workflow. */
            workflowId?: string;
            /** @description Опциональный тег версии (например, v1.0.0). */
            tag?: string;
            /** @description Дата создания версии в ISO 8601. */
            createdAt?: string;
        };
        /** @description Граф workflow, включающий ноды и связи. */
        WorkflowGraph: {
            /** @description Идентификатор версии, которой принадлежит граф. */
            versionId?: string;
            /** @description Список нод workflow. */
            nodes: components["schemas"]["Node"][];
            /** @description Список соединений между нодами. */
            connections: components["schemas"]["Connection"][];
        };
        /** @description Нода workflow. */
        Node: {
            /** @description Идентификатор ноды. */
            id?: string;
            /** @description Тип ноды (trigger, http, ab-fork и т.д.). */
            type?: string;
            /** @description Координаты ноды в редакторе графа. */
            position?: {
                /** @description Координата X. */
                x?: number;
                /** @description Координата Y. */
                y?: number;
            };
            /** @description Конфигурация ноды и дополнительные данные. */
            data?: {
                /** @description Человекочитаемое название ноды. */
                label?: string;
                /** @description Произвольная конфигурация ноды. */
                config?: Record<string, never>;
                /** @description Конфигурация A/B-теста для ноды, если применимо. */
                abConfig?: Record<string, never>;
            };
        };
        /** @description Соединение между двумя нодами workflow. */
        Connection: {
            /** @description Идентификатор соединения. */
            id: string;
            /** @description ID исходной ноды. */
            source: string;
            /** @description ID целевой ноды. */
            target: string;
            /** @description Метка исходящего порта (например, 'A' или 'B'). */
            sourceHandle?: string;
            /** @description Метка входящего порта. */
            targetHandle?: string;
        };
        /** @description Триггер запуска workflow, привязанный к ноде в графе. */
        Trigger: {
            /** @description Идентификатор триггера. */
            id?: string;
            /** @description Идентификатор workflow. */
            workflowId?: string;
            /** @description Идентификатор ноды в графе, к которой привязан триггер. */
            nodeId?: string;
            /** @description Тип триггера (webhook, cron, interval). */
            type?: string;
            /** @description Конфигурация триггера (например, cron-выражение, everySeconds). */
            config?: Record<string, never>;
            /** @description Публичный токен для webhook-триггера (генерируется на бэке). */
            token?: string;
        };
        /** @description Один запуск workflow. */
        WorkflowRun: {
            /** @description Идентификатор запуска. */
            id?: string;
            /** @description Идентификатор workflow. */
            workflowId?: string;
            /** @description Статус запуска (queued, running, success, failed). */
            status?: string;
            /** @description Время старта запуска. */
            startedAt?: string;
            /** @description Время завершения запуска. */
            finishedAt?: string;
            /** @description Входные параметры запуска. */
            input?: Record<string, never>;
            /** @description Агрегированный результат выполнения workflow. */
            output?: Record<string, never>;
        };
        /** @description Результат выполнения отдельной ноды. */
        NodeRun: {
            /** @description Идентификатор запуска ноды. */
            id?: string;
            /** @description Идентификатор запуска workflow. */
            workflowRunId?: string;
            /** @description Идентификатор ноды. */
            nodeId?: string;
            /** @description Статус выполнения ноды. */
            status?: string;
            /** @description Время старта ноды. */
            startedAt?: string;
            /** @description Время завершения ноды. */
            finishedAt?: string;
            /** @description Входные данные ноды. */
            input?: Record<string, never>;
            /** @description Выходные данные ноды. */
            output?: Record<string, never>;
            /** @description Текст ошибки, если выполнение завершилось неуспешно. */
            errorMessage?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Идентификатор workflow. */
        WorkflowId: string;
        /** @description Идентификатор версии workflow. */
        VersionId: string;
        /** @description Публичный токен webhook-триггера. */
        Token: string;
        /** @description Идентификатор запуска workflow. */
        RunId: string;
        /** @description Идентификатор запуска отдельной ноды. */
        NodeRunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
